### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by stark1tty** [trutzig89182/Mastodon-Sociologists#44]
Hello, how can I get the language keywords to display?  It does not seem like they are showing up. Thanks!

**Comment by trutzig89182** [comment]
They are not included yet, because keywords seemed more urgent to me, and I try to include the option to filter the list by clicking on a keyword.

If you want to add them, you can do so very similarly to the keywords here:
https://github.com/trutzig89182/Mastodon-Sociologists/blob/60e97f5a3e81ead1077333025853973010f7058c/assets/js/app.js#L164-L169

**Comment by trutzig89182** [comment]
user.language should contain the string from the csv file. Something like this should work

```
if ('language' in user && 'language'.trim() !== '') { //checks if the row has a cell "language" and it is not empty
  wrapper.appendChild.createTextNode(" – ") //adds – to seperate language from keywords
  const language = document.createTextNode("Language(s): " + user.language.trim()) // creates a text element for the language
  wrapper.appendChild(language) // adds this text-element to the checkbox element printed to the webpage
```

You can give it a try and make a pull request when you get it to work. I will add a branch to work on including the languages for this.

**Comment by stark1tty** [comment]
Amazing!! This is what I was trying but it broke everything (to compare for my own sake):

   const seperator = document.createTextNode(" – ")

   if ('language' in user && 'language'.trim() !== '') {
     wrapper.appendChild(seperator)

     const language = document.createTextNode("Languages: " + user.language.replaceAll(" ", ", ").replaceAll("_", " "))
     wrapper.appendChild(language)

   container.appendChild(wrapper)
  }

**Comment by stark1tty** [comment]
I tried the above and fixed formatting. It broke the list display, unfortunately. I muted this bit in the code. Is there something I am missing?

**Comment by trutzig89182** [comment]
you could make a branch with the changes and post the part that you changed here. (like this: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)

**Comment by stark1tty** [comment]
https://github.com/stark1tty/Mastodon-Archaeology/pull/3/commits/1eca469885d25ac157631971733bc89763fd1fdf

Like this? I could not get the copy option to show up.

**Comment by stark1tty** [comment]
https://github.dev/stark1tty/Mastodon-Archaeology/blob/1eca469885d25ac157631971733bc89763fd1fdf/assets/js/app.js#L171-L175

Oh, I think I got it. Sorry, a learning curve!

**Comment by trutzig89182** [comment]
I made a remark in your pull request. The sytax for adding the – was of. I tested it with the adapted syntax and it worked. Included it here in the branch https://github.com/trutzig89182/Mastodon-Sociologists/tree/wip-005-add-languages.

You could just change the change in the one commit ahead of main to you document, if you have made changes in app.js. Otherwise you could also just copy the entire file from this branch. 

I will not really include it in main for now, because I want to allow it to filter the entries by keywords – and when I have done that, I would adapt the same for languages.

**Comment by trutzig89182** [comment]
Perhaps one litte suggestion: If you don’t have an environment in which you can test the code, you could either just make a second github repository, copy all files from your repository there, and use it as test environmet and push changes from there to your main repository (like his you have a preview of your changes without them being visible to the visitors of your page from your main repository). Or you could make a dev branch, and switch the deployment of the website (in settings  -> pages) from main to this branch for a moment, in order to test it, but you can allways immediatly switch it back, if an error occurs.
In case you are using firefox, you can use the tools for web developers to identify find problems in the code (try go to "more tools", "tools for web developers" (or similar), or in the top menu, "Tools", "bowser tools" and then something like "tools for web developers" – Firefox denies switching the menue to English for me, so I can’t be 100 % sure about the wording of the last menue entry).

But that’s of course all just suggestions, as my impression was that you are making and testing the changes immediately in the main branch from which you website also runs, which can be a bit stressfull if – like me – you operate more on trial and error than on being an expert in javascript and web developpment. :)

**Comment by stark1tty** [comment]
Oh my goodness, this is all extremely helpful. I have to admit, yesterday it occurred to me that I should get a testing environment. I am more used to working with r and python for my own needs. :) Testing on the fly is usually how I work. I will definitely dive into this rabbit hole next week. Again, thank you!

**Comment by trutzig89182** [comment]
I feel you. I’m still not sure how to deal with the fact that the webpage is live from the repo. Started to use branches more, but that is also relatively new to me. …

**Comment by trutzig89182** [comment]
Close this as it seems to work for the current purpose.
